
DEVICE = "/dev/ttyUSB0"
STX = chr(2)
CR = chr(13)
LF = chr(10)

device = open("/dev/ttyUSB0", "w")
device.write(STX+'n'+CR)
device.flush()
device.write(STX +'M0500'+CR)
device.flush()
device.write(STX+'O0220'+CR)
device.flush()
device.write(STX+'V0'+CR)
device.flush()
device.write(STX+'f220'+CR)
device.flush()
device.write(STX+'D'+CR)
device.flush()
device.write(STX+'L'+CR)
device.flush()
device.write(STX+'D11'+CR)
device.flush()
device.write(STX+'A2'+CR)
device.flush()
device.write('1922A1200310010BRS - 396'+CR)
device.flush()
device.write('1922A1200310181BRS - 396'+CR)
device.flush()
device.write('Q0001'+CR)
device.flush()
device.write('E'+CR)
device.flush()
device.close()


