# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmEtiquetasCaixas.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmLabelEncomendas(object):
    def setupUi(self, frmLabelEncomendas):
        frmLabelEncomendas.setObjectName("frmLabelEncomendas")
        frmLabelEncomendas.resize(696, 488)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        frmLabelEncomendas.setFont(font)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(frmLabelEncomendas)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(frmLabelEncomendas)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.tblDocs = QtWidgets.QTableView(frmLabelEncomendas)
        self.tblDocs.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tblDocs.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblDocs.setObjectName("tblDocs")
        self.tblDocs.horizontalHeader().setVisible(True)
        self.tblDocs.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.tblDocs)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.chkEti1 = QtWidgets.QCheckBox(frmLabelEncomendas)
        self.chkEti1.setObjectName("chkEti1")
        self.horizontalLayout.addWidget(self.chkEti1)
        self.chkEti2 = QtWidgets.QCheckBox(frmLabelEncomendas)
        self.chkEti2.setObjectName("chkEti2")
        self.horizontalLayout.addWidget(self.chkEti2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.chkEti3 = QtWidgets.QCheckBox(frmLabelEncomendas)
        self.chkEti3.setObjectName("chkEti3")
        self.horizontalLayout_2.addWidget(self.chkEti3)
        self.chkEti4 = QtWidgets.QCheckBox(frmLabelEncomendas)
        self.chkEti4.setObjectName("chkEti4")
        self.horizontalLayout_2.addWidget(self.chkEti4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.btImprime = QtWidgets.QPushButton(frmLabelEncomendas)
        self.btImprime.setObjectName("btImprime")
        self.verticalLayout_2.addWidget(self.btImprime)
        self.btExporta = QtWidgets.QPushButton(frmLabelEncomendas)
        self.btExporta.setObjectName("btExporta")
        self.verticalLayout_2.addWidget(self.btExporta)
        self.btDanfe = QtWidgets.QPushButton(frmLabelEncomendas)
        self.btDanfe.setObjectName("btDanfe")
        self.verticalLayout_2.addWidget(self.btDanfe)
        self.lblStatus = QtWidgets.QLabel(frmLabelEncomendas)
        self.lblStatus.setObjectName("lblStatus")
        self.verticalLayout_2.addWidget(self.lblStatus)

        self.retranslateUi(frmLabelEncomendas)
        QtCore.QMetaObject.connectSlotsByName(frmLabelEncomendas)
        frmLabelEncomendas.setTabOrder(self.tblDocs, self.chkEti1)
        frmLabelEncomendas.setTabOrder(self.chkEti1, self.chkEti2)
        frmLabelEncomendas.setTabOrder(self.chkEti2, self.chkEti3)
        frmLabelEncomendas.setTabOrder(self.chkEti3, self.chkEti4)
        frmLabelEncomendas.setTabOrder(self.chkEti4, self.btImprime)
        frmLabelEncomendas.setTabOrder(self.btImprime, self.btExporta)
        frmLabelEncomendas.setTabOrder(self.btExporta, self.btDanfe)

    def retranslateUi(self, frmLabelEncomendas):
        _translate = QtCore.QCoreApplication.translate
        frmLabelEncomendas.setWindowTitle(_translate("frmLabelEncomendas", "Etiquetas Encomendas"))
        self.label.setText(_translate("frmLabelEncomendas", "Selecione os Envios"))
        self.chkEti1.setText(_translate("frmLabelEncomendas", "1"))
        self.chkEti2.setText(_translate("frmLabelEncomendas", "2"))
        self.chkEti3.setText(_translate("frmLabelEncomendas", "3"))
        self.chkEti4.setText(_translate("frmLabelEncomendas", "4"))
        self.btImprime.setText(_translate("frmLabelEncomendas", "Imprime Etiquetas"))
        self.btExporta.setText(_translate("frmLabelEncomendas", "Gera Arquivo Correios"))
        self.btDanfe.setText(_translate("frmLabelEncomendas", "DANFE Simplificada"))
        self.lblStatus.setText(_translate("frmLabelEncomendas", "..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    frmLabelEncomendas = QtWidgets.QDialog()
    ui = Ui_frmLabelEncomendas()
    ui.setupUi(frmLabelEncomendas)
    frmLabelEncomendas.show()
    sys.exit(app.exec_())
