# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmBaixaFrascos.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import os


class Ui_frmBaixaFrascos(object):
    def setupUi(self, frmBaixaFrascos):
        frmBaixaFrascos.setObjectName("frmBaixaFrascos")
        frmBaixaFrascos.resize(650, 556)
        self.txtData = QtWidgets.QDateEdit(frmBaixaFrascos)
        self.txtData.setGeometry(QtCore.QRect(10, 30, 151, 35))
        self.txtData.setObjectName("txtData")
        self.cmbOperador = QtWidgets.QComboBox(frmBaixaFrascos)
        self.cmbOperador.setGeometry(QtCore.QRect(200, 30, 221, 35))
        self.cmbOperador.setObjectName("cmbOperador")
        self.radioButton = QtWidgets.QRadioButton(frmBaixaFrascos)
        self.radioButton.setGeometry(QtCore.QRect(10, 93, 99, 23))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(frmBaixaFrascos)
        self.radioButton_2.setGeometry(QtCore.QRect(90, 93, 99, 23))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(frmBaixaFrascos)
        self.radioButton_3.setGeometry(QtCore.QRect(180, 93, 99, 23))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(frmBaixaFrascos)
        self.radioButton_4.setGeometry(QtCore.QRect(270, 93, 99, 23))
        self.radioButton_4.setChecked(False)
        self.radioButton_4.setObjectName("radioButton_4")
        self.tblFrascos = QtWidgets.QTableWidget(frmBaixaFrascos)
        self.tblFrascos.setGeometry(QtCore.QRect(10, 230, 621, 251))
        self.tblFrascos.setObjectName("tblFrascos")
        self.tblFrascos.setColumnCount(7)
        self.tblFrascos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        brush = QtGui.QBrush(QtGui.QColor(85, 87, 83))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tblFrascos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tblFrascos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tblFrascos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tblFrascos.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tblFrascos.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tblFrascos.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tblFrascos.setHorizontalHeaderItem(6, item)
        self.label = QtWidgets.QLabel(frmBaixaFrascos)
        self.label.setGeometry(QtCore.QRect(10, 10, 54, 17))
        self.label.setStyleSheet("color: rgb(0, 0, 205);")
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(frmBaixaFrascos)
        self.label_2.setGeometry(QtCore.QRect(200, 10, 60, 17))
        self.label_2.setStyleSheet("color: rgb(0, 0, 205);")
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(frmBaixaFrascos)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 60, 17))
        self.label_3.setStyleSheet("color: rgb(0, 0, 205);")
        self.label_3.setTextFormat(QtCore.Qt.RichText)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(frmBaixaFrascos)
        self.label_4.setGeometry(QtCore.QRect(10, 200, 60, 17))
        self.label_4.setStyleSheet("")
        self.label_4.setTextFormat(QtCore.Qt.RichText)
        self.label_4.setObjectName("label_4")
        self.btBaixar = QtWidgets.QPushButton(frmBaixaFrascos)
        self.btBaixar.setGeometry(QtCore.QRect(530, 490, 100, 36))
        self.btBaixar.setObjectName("btBaixar")
        self.label_5 = QtWidgets.QLabel(frmBaixaFrascos)
        self.label_5.setGeometry(QtCore.QRect(10, 490, 80, 17))
        self.label_5.setObjectName("label_5")
        self.lblNFrascos = QtWidgets.QLabel(frmBaixaFrascos)
        self.lblNFrascos.setGeometry(QtCore.QRect(100, 490, 54, 17))
        self.lblNFrascos.setObjectName("lblNFrascos")
        self.txtCodigo = QtWidgets.QLineEdit(frmBaixaFrascos)
        self.txtCodigo.setGeometry(QtCore.QRect(102, 150, 431, 41))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.txtCodigo.setFont(font)
        self.txtCodigo.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(249, 245, 184);")
        self.txtCodigo.setText("")
        self.txtCodigo.setAlignment(QtCore.Qt.AlignCenter)
        self.txtCodigo.setObjectName("txtCodigo")
        self.label_6 = QtWidgets.QLabel(frmBaixaFrascos)
        self.label_6.setGeometry(QtCore.QRect(10, 130, 621, 17))
        self.label_6.setStyleSheet("color: rgb(0, 0, 205);")
        self.label_6.setTextFormat(QtCore.Qt.RichText)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.pbBaixa = QtWidgets.QProgressBar(frmBaixaFrascos)
        self.pbBaixa.setGeometry(QtCore.QRect(130, 490, 371, 23))
        self.pbBaixa.setProperty("value", 0)
        self.pbBaixa.setTextVisible(False)
        self.pbBaixa.setObjectName("pbBaixa")
        self.label_7 = QtWidgets.QLabel(frmBaixaFrascos)
        self.label_7.setGeometry(QtCore.QRect(460, 0, 151, 141))
        self.label_7.setText("")
        caminho = os.path.join(".","producao","frmBaixaFrascos","images","barcode_scanner.png")
        self.label_7.setPixmap(QtGui.QPixmap(caminho))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.lblMsg = QtWidgets.QLabel(frmBaixaFrascos)
        self.lblMsg.setGeometry(QtCore.QRect(10, 510, 491, 17))
        self.lblMsg.setObjectName("lblMsg")
        self.radioButton_5 = QtWidgets.QRadioButton(frmBaixaFrascos)
        self.radioButton_5.setGeometry(QtCore.QRect(350, 93, 99, 23))
        self.radioButton_5.setChecked(True)
        self.radioButton_5.setObjectName("radioButton_5")

        self.retranslateUi(frmBaixaFrascos)
        QtCore.QMetaObject.connectSlotsByName(frmBaixaFrascos)
        frmBaixaFrascos.setTabOrder(self.txtData, self.cmbOperador)
        frmBaixaFrascos.setTabOrder(self.cmbOperador, self.radioButton)
        frmBaixaFrascos.setTabOrder(self.radioButton, self.radioButton_2)
        frmBaixaFrascos.setTabOrder(self.radioButton_2, self.radioButton_3)
        frmBaixaFrascos.setTabOrder(self.radioButton_3, self.radioButton_4)
        frmBaixaFrascos.setTabOrder(self.radioButton_4, self.txtCodigo)
        frmBaixaFrascos.setTabOrder(self.txtCodigo, self.tblFrascos)
        frmBaixaFrascos.setTabOrder(self.tblFrascos, self.btBaixar)

    def retranslateUi(self, frmBaixaFrascos):
        _translate = QtCore.QCoreApplication.translate
        frmBaixaFrascos.setWindowTitle(_translate("frmBaixaFrascos", "Baixa Frascos"))
        self.radioButton.setText(_translate("frmBaixaFrascos", "&Fungo"))
        self.radioButton_2.setText(_translate("frmBaixaFrascos", "&Bactéria"))
        self.radioButton_3.setText(_translate("frmBaixaFrascos", "&Oxidação"))
        self.radioButton_4.setText(_translate("frmBaixaFrascos", "&Plantio"))
        item = self.tblFrascos.horizontalHeaderItem(0)
        item.setText(_translate("frmBaixaFrascos", "ID"))
        item = self.tblFrascos.horizontalHeaderItem(1)
        item.setText(_translate("frmBaixaFrascos", "Merc"))
        item = self.tblFrascos.horizontalHeaderItem(2)
        item.setText(_translate("frmBaixaFrascos", "Lote"))
        item = self.tblFrascos.horizontalHeaderItem(3)
        item.setText(_translate("frmBaixaFrascos", "Clone"))
        item = self.tblFrascos.horizontalHeaderItem(4)
        item.setText(_translate("frmBaixaFrascos", "Nº Frasco"))
        item = self.tblFrascos.horizontalHeaderItem(5)
        item.setText(_translate("frmBaixaFrascos", "Motivo"))
        item = self.tblFrascos.horizontalHeaderItem(6)
        item.setText(_translate("frmBaixaFrascos", "Nº Mds"))
        self.label.setText(_translate("frmBaixaFrascos", "Data"))
        self.label_2.setText(_translate("frmBaixaFrascos", "Operador"))
        self.label_3.setText(_translate("frmBaixaFrascos", "Motivo"))
        self.label_4.setText(_translate("frmBaixaFrascos", "Frascos"))
        self.btBaixar.setText(_translate("frmBaixaFrascos", "[ F12 ] Baixar"))
        self.label_5.setText(_translate("frmBaixaFrascos", "Nº de frascos:"))
        self.lblNFrascos.setText(_translate("frmBaixaFrascos", "0"))
        self.label_6.setText(_translate("frmBaixaFrascos", "Código de Barras"))
        self.lblMsg.setText(_translate("frmBaixaFrascos", "..."))
        self.radioButton_5.setText(_translate("frmBaixaFrascos", "&Repicagem"))

