# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rptRastreadores.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmImportaRastreador(object):
    def setupUi(self, frmImportaRastreador):
        frmImportaRastreador.setObjectName("frmImportaRastreador")
        frmImportaRastreador.resize(640, 173)
        self.verticalLayout = QtWidgets.QVBoxLayout(frmImportaRastreador)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.rdJadLog = QtWidgets.QRadioButton(frmImportaRastreador)
        self.rdJadLog.setChecked(True)
        self.rdJadLog.setObjectName("rdJadLog")
        self.horizontalLayout_2.addWidget(self.rdJadLog)
        self.rdReunidas = QtWidgets.QRadioButton(frmImportaRastreador)
        self.rdReunidas.setObjectName("rdReunidas")
        self.horizontalLayout_2.addWidget(self.rdReunidas)
        self.rdCorreios = QtWidgets.QRadioButton(frmImportaRastreador)
        self.rdCorreios.setObjectName("rdCorreios")
        self.horizontalLayout_2.addWidget(self.rdCorreios)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.txtArquivo = QtWidgets.QLineEdit(frmImportaRastreador)
        self.txtArquivo.setObjectName("txtArquivo")
        self.horizontalLayout.addWidget(self.txtArquivo)
        self.btArquivo = QtWidgets.QToolButton(frmImportaRastreador)
        self.btArquivo.setObjectName("btArquivo")
        self.horizontalLayout.addWidget(self.btArquivo)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.btImportar = QtWidgets.QPushButton(frmImportaRastreador)
        self.btImportar.setObjectName("btImportar")
        self.verticalLayout.addWidget(self.btImportar)
        self.lblStatus = QtWidgets.QLabel(frmImportaRastreador)
        self.lblStatus.setObjectName("lblStatus")
        self.verticalLayout.addWidget(self.lblStatus)

        self.retranslateUi(frmImportaRastreador)
        QtCore.QMetaObject.connectSlotsByName(frmImportaRastreador)
        frmImportaRastreador.setTabOrder(self.rdJadLog, self.rdReunidas)
        frmImportaRastreador.setTabOrder(self.rdReunidas, self.rdCorreios)
        frmImportaRastreador.setTabOrder(self.rdCorreios, self.txtArquivo)
        frmImportaRastreador.setTabOrder(self.txtArquivo, self.btArquivo)
        frmImportaRastreador.setTabOrder(self.btArquivo, self.btImportar)

    def retranslateUi(self, frmImportaRastreador):
        _translate = QtCore.QCoreApplication.translate
        frmImportaRastreador.setWindowTitle(_translate("frmImportaRastreador", "Importação de Rastreadores"))
        self.rdJadLog.setText(_translate("frmImportaRastreador", "JadLog"))
        self.rdReunidas.setText(_translate("frmImportaRastreador", "Reunidas"))
        self.rdCorreios.setText(_translate("frmImportaRastreador", "Correios"))
        self.btArquivo.setText(_translate("frmImportaRastreador", "..."))
        self.btImportar.setText(_translate("frmImportaRastreador", "Importar"))
        self.lblStatus.setText(_translate("frmImportaRastreador", "..."))
