# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmInventario.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgInventario(object):
    def setupUi(self, dlgInventario):
        dlgInventario.setObjectName("dlgInventario")
        dlgInventario.resize(647, 196)
        self.verticalLayout = QtWidgets.QVBoxLayout(dlgInventario)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(dlgInventario)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.txtArquivo = QtWidgets.QLineEdit(dlgInventario)
        self.txtArquivo.setObjectName("txtArquivo")
        self.horizontalLayout.addWidget(self.txtArquivo)
        self.btSelect = QtWidgets.QToolButton(dlgInventario)
        self.btSelect.setObjectName("btSelect")
        self.horizontalLayout.addWidget(self.btSelect)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btCancelar = QtWidgets.QPushButton(dlgInventario)
        self.btCancelar.setObjectName("btCancelar")
        self.horizontalLayout_2.addWidget(self.btCancelar)
        self.btInventario = QtWidgets.QPushButton(dlgInventario)
        self.btInventario.setObjectName("btInventario")
        self.horizontalLayout_2.addWidget(self.btInventario)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.chkBackup = QtWidgets.QCheckBox(dlgInventario)
        self.chkBackup.setObjectName("chkBackup")
        self.verticalLayout.addWidget(self.chkBackup)
        self.lblMsg = QtWidgets.QLabel(dlgInventario)
        self.lblMsg.setObjectName("lblMsg")
        self.verticalLayout.addWidget(self.lblMsg)
        self.pbProgresso = QtWidgets.QProgressBar(dlgInventario)
        self.pbProgresso.setProperty("value", 0)
        self.pbProgresso.setObjectName("pbProgresso")
        self.verticalLayout.addWidget(self.pbProgresso)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(dlgInventario)
        QtCore.QMetaObject.connectSlotsByName(dlgInventario)

    def retranslateUi(self, dlgInventario):
        _translate = QtCore.QCoreApplication.translate
        dlgInventario.setWindowTitle(_translate("dlgInventario", "Processa Inventário"))
        self.label.setText(_translate("dlgInventario", "Selecione o arquivo do inventário:"))
        self.btSelect.setText(_translate("dlgInventario", "..."))
        self.btCancelar.setText(_translate("dlgInventario", "Cancelar"))
        self.btInventario.setText(_translate("dlgInventario", "Processar"))
        self.chkBackup.setText(_translate("dlgInventario", "Fazer Backup Antes de iniciar"))
        self.lblMsg.setText(_translate("dlgInventario", "..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlgInventario = QtWidgets.QDialog()
    ui = Ui_dlgInventario()
    ui.setupUi(dlgInventario)
    dlgInventario.show()
    sys.exit(app.exec_())
