# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmReservas.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from pedidos.frmReservas.clsmodTableWidget import ModTableWidget

class Ui_frmReservas(object):
    def setupUi(self, frmReservas):
        frmReservas.setObjectName("frmReservas")
        frmReservas.resize(640, 600)
        self.txtData = QtWidgets.QDateEdit(frmReservas)
        self.txtData.setGeometry(QtCore.QRect(80, 10, 160, 26))
        self.txtData.setDate(QtCore.QDate(2020, 1, 1))
        self.txtData.setObjectName("txtData")
        self.txtNome = QtWidgets.QLineEdit(frmReservas)
        self.txtNome.setGeometry(QtCore.QRect(80, 40, 351, 25))
        self.txtNome.setMaxLength(130)
        self.txtNome.setObjectName("txtNome")
        self.txtCEP = QtWidgets.QLineEdit(frmReservas)
        self.txtCEP.setGeometry(QtCore.QRect(80, 70, 80, 25))
        self.txtCEP.setToolTip("")
        self.txtCEP.setStatusTip("")
        self.txtCEP.setText("")
        self.txtCEP.setMaxLength(8)
        self.txtCEP.setAlignment(QtCore.Qt.AlignCenter)
        self.txtCEP.setObjectName("txtCEP")
        self.txtCidade = QtWidgets.QLineEdit(frmReservas)
        self.txtCidade.setGeometry(QtCore.QRect(80, 100, 211, 25))
        self.txtCidade.setMaxLength(80)
        self.txtCidade.setObjectName("txtCidade")
        self.txtEmail = QtWidgets.QLineEdit(frmReservas)
        self.txtEmail.setGeometry(QtCore.QRect(80, 160, 251, 25))
        self.txtEmail.setObjectName("txtEmail")
        self.txtQtde = QtWidgets.QLineEdit(frmReservas)
        self.txtQtde.setGeometry(QtCore.QRect(10, 200, 60, 25))
        self.txtQtde.setAlignment(QtCore.Qt.AlignCenter)
        self.txtQtde.setObjectName("txtQtde")
        self.btAcrescentar = QtWidgets.QPushButton(frmReservas)
        self.btAcrescentar.setGeometry(QtCore.QRect(530, 200, 91, 25))
        self.btAcrescentar.setObjectName("btAcrescentar")
        self.cmbVariedade = QtWidgets.QComboBox(frmReservas)
        self.cmbVariedade.setGeometry(QtCore.QRect(80, 200, 440, 25))
        self.cmbVariedade.setModelColumn(0)
        self.cmbVariedade.setObjectName("cmbVariedade")
        self.label = QtWidgets.QLabel(frmReservas)
        self.label.setGeometry(QtCore.QRect(10, 14, 64, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(frmReservas)
        self.label_2.setGeometry(QtCore.QRect(10, 43, 64, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(frmReservas)
        self.label_3.setGeometry(QtCore.QRect(10, 74, 64, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(frmReservas)
        self.label_4.setGeometry(QtCore.QRect(10, 164, 64, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(frmReservas)
        self.label_5.setGeometry(QtCore.QRect(10, 104, 64, 17))
        self.label_5.setObjectName("label_5")
        self.tblItens = ModTableWidget(frmReservas)
        self.tblItens.setGeometry(QtCore.QRect(10, 230, 611, 201))
        self.tblItens.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblItens.setTextElideMode(QtCore.Qt.ElideLeft)
        self.tblItens.setColumnCount(5)
        self.tblItens.setObjectName("tblItens")
        self.tblItens.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tblItens.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tblItens.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblItens.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.tblItens.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.tblItens.setHorizontalHeaderItem(4, item)
        self.tblItens.horizontalHeader().setCascadingSectionResizes(True)
        self.tblItens.horizontalHeader().setDefaultSectionSize(118)
        self.tblItens.verticalHeader().setVisible(False)
        self.btIncluir = QtWidgets.QPushButton(frmReservas)
        self.btIncluir.setGeometry(QtCore.QRect(540, 540, 83, 25))
        self.btIncluir.setObjectName("btIncluir")
        self.txtUF = QtWidgets.QLineEdit(frmReservas)
        self.txtUF.setGeometry(QtCore.QRect(300, 100, 30, 25))
        self.txtUF.setMaxLength(80)
        self.txtUF.setAlignment(QtCore.Qt.AlignCenter)
        self.txtUF.setPlaceholderText("")
        self.txtUF.setObjectName("txtUF")
        self.txtFone = QtWidgets.QLineEdit(frmReservas)
        self.txtFone.setGeometry(QtCore.QRect(80, 130, 211, 25))
        self.txtFone.setMaxLength(80)
        self.txtFone.setObjectName("txtFone")
        self.label_6 = QtWidgets.QLabel(frmReservas)
        self.label_6.setGeometry(QtCore.QRect(10, 134, 64, 17))
        self.label_6.setObjectName("label_6")
        self.txtPrazo = QtWidgets.QDateEdit(frmReservas)
        self.txtPrazo.setGeometry(QtCore.QRect(470, 159, 150, 26))
        self.txtPrazo.setObjectName("txtPrazo")
        self.label_7 = QtWidgets.QLabel(frmReservas)
        self.label_7.setGeometry(QtCore.QRect(380, 164, 90, 17))
        self.label_7.setObjectName("label_7")
        self.txtObs = QtWidgets.QTextEdit(frmReservas)
        self.txtObs.setGeometry(QtCore.QRect(10, 460, 611, 70))
        self.txtObs.setObjectName("txtObs")
        self.label_8 = QtWidgets.QLabel(frmReservas)
        self.label_8.setGeometry(QtCore.QRect(10, 437, 80, 17))
        self.label_8.setObjectName("label_8")

        self.retranslateUi(frmReservas)
        QtCore.QMetaObject.connectSlotsByName(frmReservas)
        frmReservas.setTabOrder(self.txtData, self.txtNome)
        frmReservas.setTabOrder(self.txtNome, self.txtCEP)
        frmReservas.setTabOrder(self.txtCEP, self.txtCidade)
        frmReservas.setTabOrder(self.txtCidade, self.txtUF)
        frmReservas.setTabOrder(self.txtUF, self.txtFone)
        frmReservas.setTabOrder(self.txtFone, self.txtEmail)
        frmReservas.setTabOrder(self.txtEmail, self.txtPrazo)
        frmReservas.setTabOrder(self.txtPrazo, self.txtQtde)
        frmReservas.setTabOrder(self.txtQtde, self.cmbVariedade)
        frmReservas.setTabOrder(self.cmbVariedade, self.btAcrescentar)
        frmReservas.setTabOrder(self.btAcrescentar, self.tblItens)
        frmReservas.setTabOrder(self.tblItens, self.btIncluir)

    def retranslateUi(self, frmReservas):
        _translate = QtCore.QCoreApplication.translate
        frmReservas.setWindowTitle(_translate("frmReservas", "Formulário de Reservas"))
        self.txtNome.setPlaceholderText(_translate("frmReservas", "Nome do cliente"))
        self.txtCEP.setInputMask(_translate("frmReservas", "99999999"))
        self.txtCEP.setPlaceholderText(_translate("frmReservas", "CEP"))
        self.txtCidade.setPlaceholderText(_translate("frmReservas", "Cidade"))
        self.txtEmail.setPlaceholderText(_translate("frmReservas", "Endereço eletrônico"))
        self.txtQtde.setPlaceholderText(_translate("frmReservas", "Qtde"))
        self.btAcrescentar.setText(_translate("frmReservas", "Acrescentar"))
        self.label.setText(_translate("frmReservas", "Data:"))
        self.label_2.setText(_translate("frmReservas", "Nome:"))
        self.label_3.setText(_translate("frmReservas", "CEP:"))
        self.label_4.setText(_translate("frmReservas", "E-mail:"))
        self.label_5.setText(_translate("frmReservas", "Cidade:"))
        item = self.tblItens.horizontalHeaderItem(0)
        item.setText(_translate("frmReservas", "Merc"))
        item = self.tblItens.horizontalHeaderItem(1)
        item.setText(_translate("frmReservas", "Clone"))
        item = self.tblItens.horizontalHeaderItem(2)
        item.setText(_translate("frmReservas", "Descrição"))
        item = self.tblItens.horizontalHeaderItem(3)
        item.setText(_translate("frmReservas", "Qtde"))
        item = self.tblItens.horizontalHeaderItem(4)
        item.setText(_translate("frmReservas", "Preço"))
        self.btIncluir.setText(_translate("frmReservas", "Incluir"))
        self.txtFone.setPlaceholderText(_translate("frmReservas", "Fone / WhatsApp"))
        self.label_6.setText(_translate("frmReservas", "Fone:"))
        self.label_7.setText(_translate("frmReservas", "Prazo Previsto:"))
        self.label_8.setText(_translate("frmReservas", "Observações:"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    frmReservas = QtWidgets.QDialog()
    ui = Ui_frmReservas()
    ui.setupUi(frmReservas)
    frmReservas.show()
    sys.exit(app.exec_())
