# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlgSelecaoClientes.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgSelClientes(object):
    def setupUi(self, dlgSelClientes):
        dlgSelClientes.setObjectName("dlgSelClientes")
        dlgSelClientes.resize(581, 341)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        dlgSelClientes.setFont(font)
        dlgSelClientes.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(dlgSelClientes)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rdPedidos = QtWidgets.QRadioButton(dlgSelClientes)
        self.rdPedidos.setChecked(True)
        self.rdPedidos.setObjectName("rdPedidos")
        self.horizontalLayout.addWidget(self.rdPedidos)
        self.rdFaturamentos = QtWidgets.QRadioButton(dlgSelClientes)
        self.rdFaturamentos.setObjectName("rdFaturamentos")
        self.horizontalLayout.addWidget(self.rdFaturamentos)
        self.rdCadastro = QtWidgets.QRadioButton(dlgSelClientes)
        self.rdCadastro.setObjectName("rdCadastro")
        self.horizontalLayout.addWidget(self.rdCadastro)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.txtPesquisa = QtWidgets.QLineEdit(dlgSelClientes)
        self.txtPesquisa.setClearButtonEnabled(True)
        self.txtPesquisa.setObjectName("txtPesquisa")
        self.verticalLayout.addWidget(self.txtPesquisa)
        self.tblClientes = QtWidgets.QTableView(dlgSelClientes)
        self.tblClientes.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tblClientes.setAlternatingRowColors(True)
        self.tblClientes.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblClientes.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblClientes.setSortingEnabled(True)
        self.tblClientes.setObjectName("tblClientes")
        self.tblClientes.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tblClientes)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btCancelar = QtWidgets.QPushButton(dlgSelClientes)
        self.btCancelar.setObjectName("btCancelar")
        self.horizontalLayout_2.addWidget(self.btCancelar)
        self.btConfirmar = QtWidgets.QPushButton(dlgSelClientes)
        self.btConfirmar.setObjectName("btConfirmar")
        self.horizontalLayout_2.addWidget(self.btConfirmar)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(dlgSelClientes)
        QtCore.QMetaObject.connectSlotsByName(dlgSelClientes)
        dlgSelClientes.setTabOrder(self.rdPedidos, self.rdFaturamentos)
        dlgSelClientes.setTabOrder(self.rdFaturamentos, self.rdCadastro)
        dlgSelClientes.setTabOrder(self.rdCadastro, self.tblClientes)
        dlgSelClientes.setTabOrder(self.tblClientes, self.btCancelar)
        dlgSelClientes.setTabOrder(self.btCancelar, self.btConfirmar)

    def retranslateUi(self, dlgSelClientes):
        _translate = QtCore.QCoreApplication.translate
        dlgSelClientes.setWindowTitle(_translate("dlgSelClientes", "Selecione o Cliente"))
        self.rdPedidos.setText(_translate("dlgSelClientes", "Pedidos Anteriores"))
        self.rdFaturamentos.setText(_translate("dlgSelClientes", "Faturamento Anteriores"))
        self.rdCadastro.setText(_translate("dlgSelClientes", "Cadastro Clientes"))
        self.txtPesquisa.setPlaceholderText(_translate("dlgSelClientes", "Localizar..."))
        self.btCancelar.setText(_translate("dlgSelClientes", "Cancelar"))
        self.btConfirmar.setText(_translate("dlgSelClientes", "Confirmar"))
