# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmRelatorioVendas.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgRelatorioVendas(object):
    def setupUi(self, dlgRelatorioVendas):
        dlgRelatorioVendas.setObjectName("dlgRelatorioVendas")
        dlgRelatorioVendas.resize(303, 111)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(dlgRelatorioVendas)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(dlgRelatorioVendas)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(dlgRelatorioVendas)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.txtDataINI = QtWidgets.QDateEdit(dlgRelatorioVendas)
        self.txtDataINI.setObjectName("txtDataINI")
        self.horizontalLayout.addWidget(self.txtDataINI)
        self.label_3 = QtWidgets.QLabel(dlgRelatorioVendas)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.txtDataFIM = QtWidgets.QDateEdit(dlgRelatorioVendas)
        self.txtDataFIM.setObjectName("txtDataFIM")
        self.horizontalLayout.addWidget(self.txtDataFIM)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.pushButton = QtWidgets.QPushButton(dlgRelatorioVendas)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(dlgRelatorioVendas)
        QtCore.QMetaObject.connectSlotsByName(dlgRelatorioVendas)
        dlgRelatorioVendas.setTabOrder(self.txtDataINI, self.txtDataFIM)
        dlgRelatorioVendas.setTabOrder(self.txtDataFIM, self.pushButton)

    def retranslateUi(self, dlgRelatorioVendas):
        _translate = QtCore.QCoreApplication.translate
        dlgRelatorioVendas.setWindowTitle(_translate("dlgRelatorioVendas", "Relatório de Vendas"))
        self.label.setText(_translate("dlgRelatorioVendas", "Selecione o período"))
        self.label_2.setText(_translate("dlgRelatorioVendas", "De:"))
        self.label_3.setText(_translate("dlgRelatorioVendas", "até:"))
        self.pushButton.setText(_translate("dlgRelatorioVendas", "Gerar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlgRelatorioVendas = QtWidgets.QDialog()
    ui = Ui_dlgRelatorioVendas()
    ui.setupUi(dlgRelatorioVendas)
    dlgRelatorioVendas.show()
    sys.exit(app.exec_())
